### ISSUE TITLE
what's the version of folium?

### ISSUE THREAD

**Issue by dumppool** [miquel-espinosa/map-sat#1]
run "python generate_points.py --npoints 1000 --name central-belt", it occur the error bellow:
_File "/data/anaconda3/envs/mapsat/lib/python3.7/site-packages/folium/raster_layers.py", line 145, in __init__
    raise ValueError("Custom tiles must have an attribution.")
ValueError: Custom tiles must have an attribution._
it also didn't work after adding attribution to the layer, 
folium.TileLayer(layer,attribution='Map data  OpenStreetMap contributors').add_to(m)
how to solve the problem?

**Comment by miquel-espinosa** [comment]
My `folium` version is `0.14.0`.
On the other hand, `folium` is not required to generate the points, but just to visualise them. So if you want to avoid the generation of the folium map, then change line 43 in the file to default to False:
```
parser.add_argument('--folium',
                        action='store_true',
                        default=False,
                        help='Create folium map.')
```
