### ISSUE TITLE
example code to run controlnet model

### ISSUE THREAD

**Issue by ale93111** [miquel-espinosa/map-sat#2]
Hello, thank you very much for your research it's very interesting
I was wondering if you could provide an example code to run the control net model?
I tried but i don't get nice results like the ones you show, this is the code i have used:

```
controlnet = ControlNetModel.from_pretrained("mespinosami/controlearth").cpu()

pipe = StableDiffusionControlNetPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", controlnet=controlnet)

image = pipe("Convert this OpenStreetMap into its satellite view", num_inference_steps=50, image=image_openstreetmap).images[0]

```

**Comment by miquel-espinosa** [comment]
Hi! Thanks for your comment.

Two things to take into account:
- the model was trained on OSM tiles at zoom level 17, so make sure that the zoom level you are using is the same. 
- it is often a good idea to generate multiple images to get different styles and variations

I have a longer script to generate the images, but here goes a simpler working example.

First download an OSM image of your liking. E.g: I download two images from Edinburgh city (OSM map at zoom=17)
```
wget https://datasets-server.huggingface.co/assets/mespinosami/map2sat-edi5k20-samples/--/default/train/11/input_image/image.png -O image1.png

wget image2.png https://datasets-server.huggingface.co/assets/mespinosami/map2sat-edi5k20-samples/--/default/train/1/input_image/image.png -O image2.png
```

Then, generate multiple images for each `control_image`:
```
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler
from PIL import Image
import torch
controlnet = ControlNetModel.from_pretrained("mespinosami/controlearth", torch_dtype=torch.float16)
pipe = StableDiffusionControlNetPipeline.from_pretrained(
        "runwayml/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=torch.float16,
        safety_checker = None, requires_safety_checker = False
    )
    
pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
pipe.enable_model_cpu_offload()

control_image_1 = Image.open('./image1.png').convert("RGB")
control_image_2 = Image.open('./image2.png').convert("RGB")
prompt = "convert this openstreetmap into its satellite view"

num_images = 5
for i in range(num_images):
    image = pipe(prompt, num_inference_steps=50, image=control_image_1).images[0].save(f'img1-generated-{i}.png')
for i in range(num_images):
    image = pipe(prompt, num_inference_steps=50, image=control_image_2).images[0].save(f'img2-generated-{i}.png')
```
The above should work out of the box, and generate images similar to these.
![examples](https://github.com/miquel-espinosa/map-sat/assets/34089118/40c5cb91-2a78-4a1e-8b21-2825266bb626)

Thanks and feel free to reopen is something doesn't work.

**Comment by miquel-espinosa** [comment]
I have too updated the README.md to include this example.
